### ISSUE TITLE
update plotly hover-over text for datasets

### ISSUE THREAD

**Issue by shapiromatron** [shapiromatron/bmds-server#100]
Currently, when hovering over a data point on a plotly plot, the format is `0.5555 +0.6666 / - 0.3333` which is long and hard to read. 

Using the hovertemplate attribute might be easiest: https://plotly.com/javascript/hover-text-and-formatting/#hovertemplate

Using the example above, the formatted text should look something like `0.555 (0.333, 0.666)`

Please check and post screenshots for both continuous and dichotomous datasets.

**Comment by shapiromatron** [comment]
Current screenshot of hover text: <img width="446" alt="Screen Shot 2021-03-23 at 4 39 21 PM" src="https://user-images.githubusercontent.com/999952/112215088-54737300-8bf6-11eb-839d-23adc35a18b2.png">

**Comment by bishwobhandari** [comment]
![continuous](https://user-images.githubusercontent.com/28153602/114589062-ed713900-9c4c-11eb-97ba-9e790d27646f.png)
![dichotomous](https://user-images.githubusercontent.com/28153602/114589066-ee09cf80-9c4c-11eb-9e5b-af1d5ddb39a7.png)
