### ISSUE TITLE
Create different DoseResponsePlots for analysis types (frequentist vs bayesian)

### ISSUE THREAD

**Issue by shapiromatron** [shapiromatron/bmds-server#121]
Previously, a single dose-response plot (and table) visualized all model outputs for frequentist and bayesian models. This plot was removed in #120, and should be restored with updated functionality.

- Previously had one DoseResponsePlot `src/components/common/DoseResponsePlot.js`
- We'll now create two plots a Frequentist Plot and a Bayesian Plot. These can be the same react component if they make sense, or could be separate components, whatever is easier to implement
- The frequentist plot will have the same behavior as the previous dose response plot. If a frequentist model is selected, then it will always be shown. If a user hovers over a row in the table, it will be shown. This feature does not currently work, so it will need to be restored.
- The bayesian plot will show all curves at the same time for bayesian data. There will be no changes when hovering. They should all be a lighter color blue with a thinner line. There is no selected-best fitting model for bayesian. In addition, we will also show a "model average" curve which will be a darker blue with a thicker line. In the future this will come from an additional dataset, but for now, just assume the model-average curve is the first row in the bayesian table.

We'll only show the frequentist table when frequentist models exist, and only show the bayesian table when bayesian models exist.

**Comment by shapiromatron** [comment]
@bishwobhandari Here's the latest dataset which can be added via the admin: 
[2021-05-18-dataset.txt](https://github.com/shapiromatron/bmds-server/files/6504313/2021-05-18-dataset.txt)

**Comment by bishwobhandari** [comment]
@shapiromatron  received. Thank you
