### ISSUE TITLE
Update scales and legend layout for some datasets

### ISSUE THREAD

**Issue by shapiromatron** [shapiromatron/bmds-server#152]
This dataset demonstrates some visual behaviors that need to be fixed:

```text
Dose	N	Mean	Std. Dev.
0	9	3302.8	410.9
0.05	10	3342.5	545.57
0.15	10	3342.5	800.35
0.5	10	1625	504.98
```
![image](https://user-images.githubusercontent.com/999952/133439987-4c0f81e0-5e73-4e91-bc0e-aab862491a04.png)

**Items to change:**

* For continuous datasets, set the max y value based on the maximum mean value plus the confidence interval, and the min y value based on the minimum mean value minus the confidence interval, instead of just the mean value.  I think dichotomous fixes the min/max between 0 and 1, but let me know if that's incorrect
* The legend in this example should not be in the top-left but the top right - can we programmatically determine legend location? Maybe if the maximum y's x value is < the dose midpoint, make top right, else top left?
* If user changes the plotly x/y scale and then hovers over a different model, the scale changes are lost. Instead, is it possible to just pass in new data instead of layout as well?

**Comment by bishwobhandari** [comment]
@shapiromatron for the third point, when they zoom and change scale , they want the same axis for other model for comparison?
right now, when they hover different model, it is triggering the plot to re render because an observable has changed in the store.

**Comment by shapiromatron** [comment]
> @shapiromatron for the third point, when they zoom and change scale , they want the same axis for other model for comparison?
> right now, when they hover different model, it is triggering the plot to re render because an observable has changed in the store.

Yep; exactly! we want to save the initial state for x/y limits, and then (re)apply them if they already exist if a model changes. Does that make sense?

**Comment by bishwobhandari** [comment]
> > @shapiromatron for the third point, when they zoom and change scale , they want the same axis for other model for comparison?
> > right now, when they hover different model, it is triggering the plot to re render because an observable has changed in the store.
> 
> Yep; exactly! we want to save the initial state for x/y limits, and then (re)apply them if they already exist if a model changes. Does that make sense?

yes make sense.
