### ISSUE TITLE
nested dichotomous frontend design

### ISSUE THREAD

**Issue by shapiromatron** [shapiromatron/bmds-server#154]
Begin designing the frontend application for the nested dichotomous model.  A subsequent request will design the backend to save the data, and more work for execution later.

Here are the items, and the enum values that we'll save as state:

- [ ] Add a new "Model Type", `Nested Dichotomous` (`ND`)
- [ ] Dataset entry example (`dose, litter_n, incidence, litter_covariate`)
![image](https://user-images.githubusercontent.com/999952/134248408-d3151c9f-82c1-4fa8-81b9-dbd328cf2e2b.png)
- [ ] Model selection options (NestedLogistic, NCTR)
![image](https://user-images.githubusercontent.com/999952/134248387-7f4a6fc6-74ee-49f0-871c-49bb5cb9e4d7.png)
- [ ] Model option sets
![image](https://user-images.githubusercontent.com/999952/134248365-e1124692-6382-48d7-b7ef-4dc47c30e1f1.png)
  - risk types - added (0) or extra (1)
  - litter specific covariates - overall mean (0) or control group mean (1)
  - background - estimated (1) or zero (0)
  - bootstrap seed - integer; default to 0

The example dataset should be:

```text
Dose	Litter Size	Incidence	Covariate
0	16	1	16
0	9	1	9
0	15	2	15
0	14	3	14
0	13	3	13
0	9	0	9
0	10	2	10
0	14	2	14
0	10	1	10
0	11	2	11
0	14	4	14
25	9	5	9
25	14	6	14
25	9	2	9
25	13	6	13
25	12	3	12
25	10	1	10
25	10	2	10
25	11	4	11
25	14	3	14
50	11	4	11
50	11	5	11
50	14	5	14
50	11	4	11
50	10	5	10
50	11	4	11
50	10	5	10
50	15	6	15
50	7	2	7
```

**Comment by bishwobhandari** [comment]
![nestedmain](https://user-images.githubusercontent.com/28153602/134972862-a54c436f-c444-4c8f-a5b4-ade72462beb6.PNG)

**Comment by bishwobhandari** [comment]
![image](https://user-images.githubusercontent.com/28153602/134972975-4213e170-f4bb-4978-82e0-9f170ba4892b.png)
