### ISSUE TITLE
Change BMRF when BMR type is modified

### ISSUE THREAD

**Issue by shapiromatron** [shapiromatron/bmds-server#185]
When the BMR Type option is modified, it should change the BMRF. This is only for continuous data.

- "Std dev" should be 1
- "Rel dev", "Hybrid extra", "Hybrid added" should be 0.1
- Point and Abs should be empty (or 1 if empty is not easy to do)

To implement, add a new mapping in the constants so this easily be modified in the future. Changing the BMR type should trigger two actions in the store, the existing action which changes the type, as well as a new action which resets the BMRF to a lookup from the mapping.

**Comment by bishwobhandari** [comment]
@shapiromatron  what if they manually input st dev as 2, and select Rel. Dev which will make bmr value to 0.1. now they want to go back and select st. dev. so selecting this will change the value back to 1. should we save the value 2 that they initially enter?

**Comment by shapiromatron** [comment]
good question! i think we can keep it simple; we don't need any memory for settings when they change. Does that work?

**Comment by bishwobhandari** [comment]
yes that will work. thanks
