### ISSUE TITLE
New links to download excel export and word report

### ISSUE THREAD

**Issue by shapiromatron** [shapiromatron/bmds-server#34]
A major requirement of the application is the ability to download the results of a bmds assessment in reports. We have some preliminary code that can generate these word and excel reports, but the purpose of this PR is just to stub out how users can access them and not actually connect them.

On the backend:

- ensure that the current API view for `excel` works and returns a valid report. If it does not, just stub out an example report.  https://github.com/shapiromatron/bmds-server/blob/master/bmds_server/jobrunner/api.py#L104. 
- create a new django rest framework view to `word` that returns reports. For now, then can be just simple stubs of empty reports that will be refined.  https://github.com/shapiromatron/bmds-server/blob/master/bmds_server/jobrunner/api.py#L104. It should return a hello world report, generated by `python-docx`
- you may need to create a new renderer to return word, use the appropriate MIME type, https://github.com/shapiromatron/bmds-server/blob/master/bmds_server/jobrunner/renderers.py
- Pass the URLs to the frontend using this pattern: https://github.com/shapiromatron/bmds-server/blob/master/bmds_server/jobrunner/views.py#L61

On the frontend:

- create a new hamburger on the top-right on the lower "blue" navbar. A user should be able to click thew links to download Excel or Download Word. The reports should download succesfully.

Python-docx: https://python-docx.readthedocs.io/en/latest/

**Comment by shapiromatron** [comment]
Mock excel report:

```python
import io
from pathlib import Path
from docx import Document
import pandas as pd

# write excel file
df = pd.DataFrame(data=dict(a=[1,2,3],b=[4,5,6]))
f = io.BytesIO()
df.to_excel(f, index=False)
Path('~/Desktop/test.xlsx').expanduser().write_bytes(f.getvalue())

# write word file
f = io.BytesIO()
document = Document()
document.add_heading('Hello world', 0)
document.save(f)
Path('~/Desktop/test.docx').expanduser().write_bytes(f.getvalue())
```

In both cases, `f` is a file-like object, and `f.getvalue()` are the bytes for the excel/word object.

**Comment by bishwobhandari** [comment]
PR merged in.
