### ISSUE TITLE
update outputs with new bmds format

### ISSUE THREAD

**Issue by shapiromatron** [shapiromatron/bmds-server#94]
Previously, outputs which were created in BMDS were in a format which was speculative, but more recently, the format has stabilized and should be close to final [BMDS#33](https://github.com/shapiromatron/bmds/pull/33).

Based on these changes, output values will need to be updated in the user interface of bmds-online.

- [x] Update summary table to pull values from new locations
- [x] Update summary plot to pull values from new locations
- [x] Update output modal components to pull values from new locations

**Design considerations: ** Generally the data format for continuous and dichotomous datasets are pretty different. Therefore, it is appropriate to separate components for output tables as needed for each table type. If you really want to use the same component, then just bake the constants directly in the file, since they'd only be used in one place.  Feel free to discuss if it'd be valuable.

- Example input, outputs, and summary tables are shown here: [example-outputs.txt](https://github.com/shapiromatron/bmds-server/files/5998884/example-outputs.txt)
- The text-report tables were generated using code in the `tbl()` methods here, which may be instructive in how to build the html tables since the data structure is identical: 
  - https://github.com/shapiromatron/bmds/blob/main/bmds/bmds3/types/dichotomous.py#L195-L200
  - https://github.com/shapiromatron/bmds/blob/main/bmds/bmds3/types/continuous.py#L226-L242

**Comment by bishwobhandari** [comment]
updated outputs pulling data from new format.
